name: anime_vault
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #state management
  flutter_bloc: ^8.1.3

  #generate data classes
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1

  #comparing objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.6

  #date format
  intl: ^0.19.0

  #request to api
  retrofit: ^4.0.3

  #hooks
  flutter_hooks: ^0.20.4

  #cached images
  cached_network_image: ^3.3.1

  #store env variable
  flutter_dotenv: ^5.1.0

  #http networking
  dio: ^5.4.0

  #svg
  flutter_svg: ^2.0.9

  #JSON serialization and deserialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  retrofit_generator: ^8.0.6

  build_runner: ^2.4.8

  flutter_gen_runner: ^5.4.0

  json_serializable: ^6.7.1

flutter_gen:
  output: lib/core/gen/

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
